version: '3.3'
services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/config.yaml
    ports:
      - "4317:4317"
    networks: [exporter]
    depends_on: [zipkin]

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks: [exporter]

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
    networks: [exporter]

networks:
  exporter:
